/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FlexJustifyContent } from "./util/justify-content.type";
export namespace Components {
  interface DColumn {
    justifyContent: FlexJustifyContent;
  }
  interface DRow {
    justifyContent: FlexJustifyContent;
  }
}
declare global {
  interface HTMLDColumnElement extends Components.DColumn, HTMLStencilElement {}
  var HTMLDColumnElement: {
    prototype: HTMLDColumnElement;
    new (): HTMLDColumnElement;
  };
  interface HTMLDRowElement extends Components.DRow, HTMLStencilElement {}
  var HTMLDRowElement: {
    prototype: HTMLDRowElement;
    new (): HTMLDRowElement;
  };
  interface HTMLElementTagNameMap {
    "d-column": HTMLDColumnElement;
    "d-row": HTMLDRowElement;
  }
}
declare namespace LocalJSX {
  interface DColumn {
    justifyContent?: FlexJustifyContent;
  }
  interface DRow {
    justifyContent?: FlexJustifyContent;
  }
  interface IntrinsicElements {
    "d-column": DColumn;
    "d-row": DRow;
  }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      "d-column": LocalJSX.DColumn & JSXBase.HTMLAttributes<HTMLDColumnElement>;
      "d-row": LocalJSX.DRow & JSXBase.HTMLAttributes<HTMLDRowElement>;
    }
  }
}
