/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DRow {
    }
}
declare global {
    interface HTMLDRowElement extends Components.DRow, HTMLStencilElement {
    }
    var HTMLDRowElement: {
        prototype: HTMLDRowElement;
        new (): HTMLDRowElement;
    };
    interface HTMLElementTagNameMap {
        "d-row": HTMLDRowElement;
    }
}
declare namespace LocalJSX {
    interface DRow {
    }
    interface IntrinsicElements {
        "d-row": DRow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "d-row": LocalJSX.DRow & JSXBase.HTMLAttributes<HTMLDRowElement>;
        }
    }
}
